AllCops:
  Exclude:
    - 'tests/*.rb'    
  TargetRubyVersion: 2.6

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 200
  
Metrics/CyclomaticComplexity:
  Max: 15

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 40